<?php
    Header("Content-Type: text/html");

    echo "      <div data-role='collapsible'>\n";
    echo "          <h2>Zona Giorno</h2>\n";
    echo "          <ul data-role='listview' data-split-theme='a' class='listviewclass'>\n";
    echo "              <li>\n";
    echo "                  <fieldset class='ui-grid-d'>\n";
    echo "                      <div class='ui-block-a' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room0split0mode'>Mode</label>\n";
    echo "                              <select name='room0split0mode' id='room0split0mode' data-mini='true'>\n";
    echo "                                  <option value='0'>Off</option>\n";
    echo "                                  <option value='1'>Warm</option>\n";
    echo "                                  <option value='2'>Cool</option>\n";
    echo "                                  <option value='3'>Fan</option>\n";
    echo "                                  <option value='4'>Dry</option>\n";
    echo "                                  <option value='5'>Auto</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-b' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room0split0temp'>Temp</label>\n";
    echo "                              <select name='room0split0temp' id='room0split0temp' data-mini='true'>\n";
    echo "                                  <option value='16'>16</option>\n";
    echo "                                  <option value='17'>17</option>\n";
    echo "                                  <option value='18'>18</option>\n";
    echo "                                  <option value='19'>19</option>\n";
    echo "                                  <option value='20'>20</option>\n";
    echo "                                  <option value='21'>21</option>\n";
    echo "                                  <option value='22'>22</option>\n";
    echo "                                  <option value='23'>23</option>\n";
    echo "                                  <option value='24'>24</option>\n";
    echo "                                  <option value='25'>25</option>\n";
    echo "                                  <option value='26'>26</option>\n";
    echo "                                  <option value='27'>27</option>\n";
    echo "                                  <option value='28'>28</option>\n";
    echo "                                  <option value='29'>29</option>\n";
    echo "                                  <option value='30'>30</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-c' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room0split0speed'>Speed</label>\n";
    echo "                              <select name='room0split0speed' id='room0split0speed' data-mini='true'>\n";
    echo "                                  <option value='0'>Auto</option>\n";
    echo "                                  <option value='1'>Min</option>\n";
    echo "                                  <option value='2'>Med</option>\n";
    echo "                                  <option value='3'>Max</option>\n";
    echo "                                  <option value='4'>Silent</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-d' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <input name='room0split0swing' id='room0split0swing' data-mini='true' type='checkbox'>\n";
    echo "                              <label for='room0split0swing'>Swing</label>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-e' style='width:12%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <button class='ui-btn ui-icon-power ui-btn-icon-notext' name='room0split0button' id='room0split0button'>Go</button>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                  </fieldset>\n";
    echo "              </li>\n";
    echo "          </ul>\n";
    echo "      </div>\n";
    echo "\n";
    echo "      <div data-role='collapsible'>\n";
    echo "          <h2>Studio</h2>\n";
    echo "          <ul data-role='listview' data-split-theme='a' class='listviewclass'>\n";
    echo "              <li>\n";
    echo "                  <fieldset class='ui-grid-d'>\n";
    echo "                      <div class='ui-block-a' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room1split0mode'>Mode</label>\n";
    echo "                              <select name='room1split0mode' id='room1split0mode' data-mini='true'>\n";
    echo "                                  <option value='0'>Off</option>\n";
    echo "                                  <option value='1'>Warm</option>\n";
    echo "                                  <option value='2'>Cool</option>\n";
    echo "                                  <option value='3'>Fan</option>\n";
    echo "                                  <option value='4'>Dry</option>\n";
    echo "                                  <option value='5'>Auto</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-b' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room1split0temp'>Temp</label>\n";
    echo "                              <select name='room1split0temp' id='room1split0temp' data-mini='true'>\n";
    echo "                                  <option value='16'>16</option>\n";
    echo "                                  <option value='17'>17</option>\n";
    echo "                                  <option value='18'>18</option>\n";
    echo "                                  <option value='19'>19</option>\n";
    echo "                                  <option value='20'>20</option>\n";
    echo "                                  <option value='21'>21</option>\n";
    echo "                                  <option value='22'>22</option>\n";
    echo "                                  <option value='23'>23</option>\n";
    echo "                                  <option value='24'>24</option>\n";
    echo "                                  <option value='25'>25</option>\n";
    echo "                                  <option value='26'>26</option>\n";
    echo "                                  <option value='27'>27</option>\n";
    echo "                                  <option value='28'>28</option>\n";
    echo "                                  <option value='29'>29</option>\n";
    echo "                                  <option value='30'>30</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-c' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room1split0speed'>Speed</label>\n";
    echo "                              <select name='room1split0speed' id='room1split0speed' data-mini='true'>\n";
    echo "                                  <option value='0'>Auto</option>\n";
    echo "                                  <option value='1'>Min</option>\n";
    echo "                                  <option value='2'>Med</option>\n";
    echo "                                  <option value='3'>Max</option>\n";
    echo "                                  <option value='4'>Silent</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-d' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <input name='room1split0swing' id='room1split0swing' data-mini='true' type='checkbox'>\n";
    echo "                              <label for='room1split0swing'>Swing</label>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-e' style='width:12%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <button class='ui-btn ui-icon-power ui-btn-icon-notext' name='room1split0button' id='room1split0button'>Go</button>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                  </fieldset>\n";
    echo "              </li>\n";
    echo "          </ul>\n";
    echo "      </div>\n";
    echo "\n";
    echo "      <div data-role='collapsible'>\n";
    echo "          <h2>Zona Notte</h2>\n";
    echo "          <ul data-role='listview' data-split-theme='a' class='listviewclass'>\n";
    echo "              <li>\n";
    echo "                  <fieldset class='ui-grid-d'>\n";
    echo "                      <div class='ui-block-a' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room2split0mode'>Mode</label>\n";
    echo "                              <select name='room2split0mode' id='room2split0mode' data-mini='true'>\n";
    echo "                                  <option value='0'>Off</option>\n";
    echo "                                  <option value='1'>Warm</option>\n";
    echo "                                  <option value='2'>Cool</option>\n";
    echo "                                  <option value='3'>Fan</option>\n";
    echo "                                  <option value='4'>Dry</option>\n";
    echo "                                  <option value='5'>Auto</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-b' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room2split0temp'>Temp</label>\n";
    echo "                              <select name='room2split0temp' id='room2split0temp' data-mini='true'>\n";
    echo "                                  <option value='16'>16</option>\n";
    echo "                                  <option value='17'>17</option>\n";
    echo "                                  <option value='18'>18</option>\n";
    echo "                                  <option value='19'>19</option>\n";
    echo "                                  <option value='20'>20</option>\n";
    echo "                                  <option value='21'>21</option>\n";
    echo "                                  <option value='22'>22</option>\n";
    echo "                                  <option value='23'>23</option>\n";
    echo "                                  <option value='24'>24</option>\n";
    echo "                                  <option value='25'>25</option>\n";
    echo "                                  <option value='26'>26</option>\n";
    echo "                                  <option value='27'>27</option>\n";
    echo "                                  <option value='28'>28</option>\n";
    echo "                                  <option value='29'>29</option>\n";
    echo "                                  <option value='30'>30</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-c' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room2split0speed'>Speed</label>\n";
    echo "                              <select name='room2split0speed' id='room2split0speed' data-mini='true'>\n";
    echo "                                  <option value='0'>Auto</option>\n";
    echo "                                  <option value='1'>Min</option>\n";
    echo "                                  <option value='2'>Med</option>\n";
    echo "                                  <option value='3'>Max</option>\n";
    echo "                                  <option value='4'>Silent</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-d' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <input name='room2split0swing' id='room2split0swing' data-mini='true' type='checkbox'>\n";
    echo "                              <label for='room2split0swing'>Swing</label>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-e' style='width:12%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <button class='ui-btn ui-icon-power ui-btn-icon-notext' name='room2split0button' id='room2split0button'>Go</button>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                  </fieldset>\n";
    echo "              </li>\n";
    echo "          </ul>\n";
    echo "      </div>\n";
    echo "\n";
    echo "      <div data-role='collapsible'>\n";
    echo "          <h2>Matrimoniale</h2>\n";
    echo "          <ul data-role='listview' data-split-theme='a' class='listviewclass'>\n";
    echo "              <li>\n";
    echo "                  <fieldset class='ui-grid-d'>\n";
    echo "                      <div class='ui-block-a' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room3split0mode'>Mode</label>\n";
    echo "                              <select name='room3split0mode' id='room3split0mode' data-mini='true'>\n";
    echo "                                  <option value='0'>Off</option>\n";
    echo "                                  <option value='1'>Warm</option>\n";
    echo "                                  <option value='2'>Cool</option>\n";
    echo "                                  <option value='3'>Fan</option>\n";
    echo "                                  <option value='4'>Dry</option>\n";
    echo "                                  <option value='5'>Auto</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-b' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room3split0temp'>Temp</label>\n";
    echo "                              <select name='room3split0temp' id='room3split0temp' data-mini='true'>\n";
    echo "                                  <option value='16'>16</option>\n";
    echo "                                  <option value='17'>17</option>\n";
    echo "                                  <option value='18'>18</option>\n";
    echo "                                  <option value='19'>19</option>\n";
    echo "                                  <option value='20'>20</option>\n";
    echo "                                  <option value='21'>21</option>\n";
    echo "                                  <option value='22'>22</option>\n";
    echo "                                  <option value='23'>23</option>\n";
    echo "                                  <option value='24'>24</option>\n";
    echo "                                  <option value='25'>25</option>\n";
    echo "                                  <option value='26'>26</option>\n";
    echo "                                  <option value='27'>27</option>\n";
    echo "                                  <option value='28'>28</option>\n";
    echo "                                  <option value='29'>29</option>\n";
    echo "                                  <option value='30'>30</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-c' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <label for='room3split0speed'>Speed</label>\n";
    echo "                              <select name='room3split0speed' id='room3split0speed' data-mini='true'>\n";
    echo "                                  <option value='0'>Auto</option>\n";
    echo "                                  <option value='1'>Min</option>\n";
    echo "                                  <option value='2'>Med</option>\n";
    echo "                                  <option value='3'>Max</option>\n";
    echo "                                  <option value='4'>Silent</option>\n";
    echo "                              </select>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-d' style='width:22%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <input name='room3split0swing' id='room3split0swing' data-mini='true' type='checkbox'>\n";
    echo "                              <label for='room3split0swing'>Swing</label>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                      <div class='ui-block-e' style='width:12%'>\n";
    echo "                          <div class='ui-field-contain'>\n";
    echo "                              <button class='ui-btn ui-icon-power ui-btn-icon-notext' name='room3split0button' id='room3split0button'>Go</button>\n";
    echo "                          </div>\n";
    echo "                      </div>\n";
    echo "                  </fieldset>\n";
    echo "              </li>\n";
    echo "          </ul>\n";
    echo "      </div>\n";
?>
